export const course = {
  id: "analytical-chemistry-1",
  title: "Analytische Chemie 1",
  subtitle: "Spektrometrie, Elektrochemie & Sensorik",
  icon: "🔭",
  color: "#3b82f6",
  level: "Uni",
  description: "Spektrometrische und elektrochemische Analysemethoden: Lambert-Beer, FT-IR, Raman, Fluoreszenz, Röntgenspektroskopie, Potentiometrie, Voltammetrie, Chemosensoren, Chromatographie und Statistik.",
  topics: [
    "01-grundlagen-spektroskopie",
    "02-lambert-beer",
    "03-fluoreszenz-lumineszenz",
    "04-ftir-raman",
    "05-roentgenspektroskopie",
    "06-elektrochemische-grundlagen",
    "07-potentiometrie-nernst",
    "08-voltammetrie-coulometrie",
    "09-chemosensoren",
    "10-statistik-qualitaet",
    "11-saeurebase-ph",
    "12-faellungsreaktionen",
    "13-chromatographie-grundlagen",
    "14-trennverfahren-gc-hplc",
    "15-kalibrierung-standardaddition",
    "16-atomspektrometrie",
    "17-elektroden-faellungstitration",
    "18-fehlerrechnung",
  ],
  totalTopics: 18,
  estimatedHours: 40,
};
