export const course = {
  id: "organic-chemistry",
  title: "Heterocyclic Chemistry & Drug Synthesis",
  subtitle: "Synthesis, Reactivity & Medicinal Chemistry",
  icon: "🧬",
  color: "#8b5cf6",
  level: "Uni",
  description: "Aromatic heterocycles, cycloadditions, cyclocondensations, SEAr regioselectivity, reaction mechanisms, bioisosteres and skeletal editing.",
  topics: [
    "01-introduction",
    "02-pyridines",
    "03-five-ring-one-heteroatom",
    "04-five-ring-two-heteroatoms",
    "05-cycloadditions",
    "06-cyclocondensations",
    "07-sear-regioselectivity",
    "08-mechanisms",
    "09-bioisosteres-skeletal-editing",
  ],
  totalTopics: 9,
  estimatedHours: 25,
};
