import type { Kurs } from '../../content/schema'

export const course = {
  id: "experimentale-physik-2",
  title: "Experimentalphysik 2",
  subtitle: "Elektrizität, Magnetismus und Optik",
  icon: "🔭",
  color: "#3b82f6",
  level: "Uni",
  description: "",
  topics: [
    "01-galilei-transformation",
    "02-elektrostatik",
    "03-elektrischer-strom",
    "04-ohmsches-gesetz",
    "05-kirchhoff-und-schaltungen",
    "06-spannungsquellen-innenwiderstand",
    "07-elektrische-messungen",
    "08-hgue-und-leistung",
    "09-statische-magnetfelder",
    "10-zeitlich-veraenderliche-felder",
    "11-elektrotechnische-anwendungen",
    "12-elektromagnetische-wellen",
    "13-elektromagnetische-wellen-im-vakuum",
    "14-elektromagnetische-wellen-in-materie",
    "15-geometrische-optik",
    "16-interferenz-und-kohaerenz",
    "17-young-doppelspalt",
    "18-michelson-interferometer",
    "19-mach-zehnder-interferometer",
    "20-planparallele-platte-zweistrahl",
    "21-fabry-perot-interferometer",
    "22-beugung-einzelspalt",
    "23-beugung-reziprozitaet",
    "24-beugung-kreisfoermiges-objekt",
    "25-beugungsgitter",
    "26-fresnel-zonen",
    "27-winkelvergroesserung-und-lupe",
    "28-fernrohre-kepler-galilei",
    "29-mikroskop",
    "30-aufloesungsvermoegen-optischer-instrumente",
  ],
  totalTopics: 30,
  estimatedHours: 37,
  sprache: "de",
  formelsatz: "chemie",
  entwurf: true,
  gruppen: [],
  ordnung: {
    titel: "Schriftliche Prüfung",
    fragen: 20,
    punkteJeFrage: 1.6,
    regel: "streng",
    zeitMinuten: 120,
    noten: [{ ab: 29, note: "sehr gut" }, { ab: 25, note: "gut" }, { ab: 21, note: "befriedigend" }, { ab: 17, note: "genügend" }],
    gebiete: [
      { id: "bezugssysteme-und-elektrostatik", titel: "Bezugssysteme und Elektrostatik", fragen: 1,
        topics: ["01-galilei-transformation", "02-elektrostatik"] },
      { id: "gleichstromkreise", titel: "Gleichstromkreise", fragen: 4,
        topics: ["03-elektrischer-strom", "04-ohmsches-gesetz", "05-kirchhoff-und-schaltungen", "06-spannungsquellen-innenwiderstand", "07-elektrische-messungen", "08-hgue-und-leistung"] },
      { id: "magnetfelder-und-induktion", titel: "Magnetfelder und Induktion", fragen: 2,
        topics: ["09-statische-magnetfelder", "10-zeitlich-veraenderliche-felder", "11-elektrotechnische-anwendungen"] },
      { id: "elektromagnetische-wellen", titel: "Elektromagnetische Wellen", fragen: 2,
        topics: ["12-elektromagnetische-wellen", "13-elektromagnetische-wellen-im-vakuum", "14-elektromagnetische-wellen-in-materie"] },
      { id: "geometrische-optik", titel: "Geometrische Optik", fragen: 1,
        topics: ["15-geometrische-optik"] },
      { id: "interferenz", titel: "Interferenz", fragen: 4,
        topics: ["16-interferenz-und-kohaerenz", "17-young-doppelspalt", "18-michelson-interferometer", "19-mach-zehnder-interferometer", "20-planparallele-platte-zweistrahl", "21-fabry-perot-interferometer"] },
      { id: "beugung", titel: "Beugung", fragen: 3,
        topics: ["22-beugung-einzelspalt", "23-beugung-reziprozitaet", "24-beugung-kreisfoermiges-objekt", "25-beugungsgitter", "26-fresnel-zonen"] },
      { id: "optische-instrumente", titel: "Optische Instrumente", fragen: 3,
        topics: ["27-winkelvergroesserung-und-lupe", "28-fernrohre-kepler-galilei", "29-mikroskop", "30-aufloesungsvermoegen-optischer-instrumente"] },
    ],
  },
} satisfies Kurs;
// ORDNUNG-JSON: {"titel":"Schriftliche Prüfung","fragen":20,"punkteJeFrage":1.6,"regel":"streng","zeitMinuten":120,"noten":[{"ab":29,"note":"sehr gut"},{"ab":25,"note":"gut"},{"ab":21,"note":"befriedigend"},{"ab":17,"note":"genügend"}],"gebiete":[{"id":"bezugssysteme-und-elektrostatik","titel":"Bezugssysteme und Elektrostatik","topics":["01-galilei-transformation","02-elektrostatik"],"fragen":1},{"id":"gleichstromkreise","titel":"Gleichstromkreise","topics":["03-elektrischer-strom","04-ohmsches-gesetz","05-kirchhoff-und-schaltungen","06-spannungsquellen-innenwiderstand","07-elektrische-messungen","08-hgue-und-leistung"],"fragen":4},{"id":"magnetfelder-und-induktion","titel":"Magnetfelder und Induktion","topics":["09-statische-magnetfelder","10-zeitlich-veraenderliche-felder","11-elektrotechnische-anwendungen"],"fragen":2},{"id":"elektromagnetische-wellen","titel":"Elektromagnetische Wellen","topics":["12-elektromagnetische-wellen","13-elektromagnetische-wellen-im-vakuum","14-elektromagnetische-wellen-in-materie"],"fragen":2},{"id":"geometrische-optik","titel":"Geometrische Optik","topics":["15-geometrische-optik"],"fragen":1},{"id":"interferenz","titel":"Interferenz","topics":["16-interferenz-und-kohaerenz","17-young-doppelspalt","18-michelson-interferometer","19-mach-zehnder-interferometer","20-planparallele-platte-zweistrahl","21-fabry-perot-interferometer"],"fragen":4},{"id":"beugung","titel":"Beugung","topics":["22-beugung-einzelspalt","23-beugung-reziprozitaet","24-beugung-kreisfoermiges-objekt","25-beugungsgitter","26-fresnel-zonen"],"fragen":3},{"id":"optische-instrumente","titel":"Optische Instrumente","topics":["27-winkelvergroesserung-und-lupe","28-fernrohre-kepler-galilei","29-mikroskop","30-aufloesungsvermoegen-optischer-instrumente"],"fragen":3}]}
