import type { Kurs } from '../../content/schema'

export const course = {
  id: "experimentale-physik-2",
  title: "Experimentalphysik 2",
  subtitle: "Elektrizität, Magnetismus und Optik",
  icon: "🔭",
  color: "#3b82f6",
  level: "Uni",
  description: "",
  topics: [
    "01-galilei-transformation",
    "02-elektrostatik",
    "03-elektrischer-strom",
    "04-ohmsches-gesetz",
    "05-kirchhoff-und-schaltungen",
    "06-spannungsquellen-innenwiderstand",
    "07-elektrische-messungen",
    "08-hgue-und-leistung",
    "09-statische-magnetfelder",
    "10-zeitlich-veraenderliche-felder",
    "11-elektrotechnische-anwendungen",
    "12-elektromagnetische-wellen",
    "13-elektromagnetische-wellen-im-vakuum",
    "14-elektromagnetische-wellen-in-materie",
    "15-geometrische-optik",
    "16-interferenz-und-kohaerenz",
    "17-young-doppelspalt",
    "18-michelson-interferometer",
    "19-mach-zehnder-interferometer",
    "20-planparallele-platte-zweistrahl",
    "21-fabry-perot-interferometer",
    "22-beugung-einzelspalt",
    "23-beugung-reziprozitaet",
    "24-beugung-kreisfoermiges-objekt",
    "25-beugungsgitter",
    "26-fresnel-zonen",
    "27-winkelvergroesserung-und-lupe",
    "28-fernrohre-kepler-galilei",
    "29-mikroskop",
    "30-aufloesungsvermoegen-optischer-instrumente",
  ],
  totalTopics: 30,
  estimatedHours: 37,
  sprache: "de",
  formelsatz: "chemie",
  entwurf: true,
  gruppen: [],
} satisfies Kurs;
