-- Karteikarten-Kennungen von der Position auf einen stabilen Schlüssel umstellen.
--
-- Bisher war die Kennung `<thema>#<position>`. Eine Karte oben einfügen hat
-- damit still den Lernplan aller folgenden Karten verschoben: die Wiederholung
-- zeigte auf die Karte daneben. Die neue Kennung kommt aus der Vorderseite
-- (siehe src/content/kartenId.ts) und bleibt beim Umsortieren gleich.
--
-- Drei eigenständige Anweisungen, keine temporäre Tabelle: der SQL-Editor
-- führt jede Anweisung für sich aus, eine Temp-Tabelle wäre dazwischen weg.
-- Der Reihe nach ausführen — Schritt 3 räumt auf, was Schritt 1 nicht fand.

-- 1. Karten mit bekannter Zuordnung umschreiben.
update reviews r
   set item_id = u.neu
  from (values
    ('analytical-chemistry-1', '01-grundlagen-spektroskopie#0', 'card:01-grundlagen-spektroskopie:0r9xh85'),
    ('analytical-chemistry-1', '01-grundlagen-spektroskopie#1', 'card:01-grundlagen-spektroskopie:1wahz4s'),
    ('analytical-chemistry-1', '01-grundlagen-spektroskopie#2', 'card:01-grundlagen-spektroskopie:1i7e5ou'),
    ('analytical-chemistry-1', '01-grundlagen-spektroskopie#3', 'card:01-grundlagen-spektroskopie:0jll9w1'),
    ('analytical-chemistry-1', '01-grundlagen-spektroskopie#4', 'card:01-grundlagen-spektroskopie:1iyunxu'),
    ('analytical-chemistry-1', '01-grundlagen-spektroskopie#5', 'card:01-grundlagen-spektroskopie:0usyg74'),
    ('analytical-chemistry-1', '02-lambert-beer#0', 'card:02-lambert-beer:1nos00w'),
    ('analytical-chemistry-1', '02-lambert-beer#1', 'card:02-lambert-beer:10hw68u'),
    ('analytical-chemistry-1', '02-lambert-beer#2', 'card:02-lambert-beer:04dacye'),
    ('analytical-chemistry-1', '02-lambert-beer#3', 'card:02-lambert-beer:0vxol5c'),
    ('analytical-chemistry-1', '02-lambert-beer#4', 'card:02-lambert-beer:0at6mqo'),
    ('analytical-chemistry-1', '02-lambert-beer#5', 'card:02-lambert-beer:0hlta5g'),
    ('analytical-chemistry-1', '03-fluoreszenz-lumineszenz#0', 'card:03-fluoreszenz-lumineszenz:0522g49'),
    ('analytical-chemistry-1', '03-fluoreszenz-lumineszenz#1', 'card:03-fluoreszenz-lumineszenz:1d9ei56'),
    ('analytical-chemistry-1', '03-fluoreszenz-lumineszenz#2', 'card:03-fluoreszenz-lumineszenz:0usyg74'),
    ('analytical-chemistry-1', '03-fluoreszenz-lumineszenz#3', 'card:03-fluoreszenz-lumineszenz:1feba0a'),
    ('analytical-chemistry-1', '03-fluoreszenz-lumineszenz#4', 'card:03-fluoreszenz-lumineszenz:1ao8eit'),
    ('analytical-chemistry-1', '03-fluoreszenz-lumineszenz#5', 'card:03-fluoreszenz-lumineszenz:12cad58'),
    ('analytical-chemistry-1', '04-ftir-raman#0', 'card:04-ftir-raman:1g42tf7'),
    ('analytical-chemistry-1', '04-ftir-raman#1', 'card:04-ftir-raman:0z5u3e5'),
    ('analytical-chemistry-1', '04-ftir-raman#2', 'card:04-ftir-raman:04slm67'),
    ('analytical-chemistry-1', '04-ftir-raman#3', 'card:04-ftir-raman:0g4y1mb'),
    ('analytical-chemistry-1', '04-ftir-raman#4', 'card:04-ftir-raman:0gj5icy'),
    ('analytical-chemistry-1', '04-ftir-raman#5', 'card:04-ftir-raman:0n2uuz4'),
    ('analytical-chemistry-1', '05-roentgenspektroskopie#0', 'card:05-roentgenspektroskopie:0jltk3e'),
    ('analytical-chemistry-1', '05-roentgenspektroskopie#1', 'card:05-roentgenspektroskopie:1juva7r'),
    ('analytical-chemistry-1', '05-roentgenspektroskopie#2', 'card:05-roentgenspektroskopie:1g4r1bj'),
    ('analytical-chemistry-1', '05-roentgenspektroskopie#3', 'card:05-roentgenspektroskopie:083w12j'),
    ('analytical-chemistry-1', '05-roentgenspektroskopie#4', 'card:05-roentgenspektroskopie:0bd8kdk'),
    ('analytical-chemistry-1', '05-roentgenspektroskopie#5', 'card:05-roentgenspektroskopie:0mb1d4z'),
    ('analytical-chemistry-1', '06-elektrochemische-grundlagen#0', 'card:06-elektrochemische-grundlagen:0nj0tc8'),
    ('analytical-chemistry-1', '06-elektrochemische-grundlagen#1', 'card:06-elektrochemische-grundlagen:1v93cpk'),
    ('analytical-chemistry-1', '06-elektrochemische-grundlagen#2', 'card:06-elektrochemische-grundlagen:07v04ha'),
    ('analytical-chemistry-1', '06-elektrochemische-grundlagen#3', 'card:06-elektrochemische-grundlagen:011smjf'),
    ('analytical-chemistry-1', '06-elektrochemische-grundlagen#4', 'card:06-elektrochemische-grundlagen:01wmd2i'),
    ('analytical-chemistry-1', '06-elektrochemische-grundlagen#5', 'card:06-elektrochemische-grundlagen:08tel9p'),
    ('analytical-chemistry-1', '07-potentiometrie-nernst#0', 'card:07-potentiometrie-nernst:1adsfli'),
    ('analytical-chemistry-1', '07-potentiometrie-nernst#1', 'card:07-potentiometrie-nernst:085mres'),
    ('analytical-chemistry-1', '07-potentiometrie-nernst#2', 'card:07-potentiometrie-nernst:0aqggm7'),
    ('analytical-chemistry-1', '07-potentiometrie-nernst#3', 'card:07-potentiometrie-nernst:1ujiprb'),
    ('analytical-chemistry-1', '07-potentiometrie-nernst#4', 'card:07-potentiometrie-nernst:0m4gkvv'),
    ('analytical-chemistry-1', '07-potentiometrie-nernst#5', 'card:07-potentiometrie-nernst:0s5g3zz'),
    ('analytical-chemistry-1', '08-voltammetrie-coulometrie#0', 'card:08-voltammetrie-coulometrie:1ef2p8y'),
    ('analytical-chemistry-1', '08-voltammetrie-coulometrie#1', 'card:08-voltammetrie-coulometrie:0m35yuh'),
    ('analytical-chemistry-1', '08-voltammetrie-coulometrie#2', 'card:08-voltammetrie-coulometrie:1s609ou'),
    ('analytical-chemistry-1', '08-voltammetrie-coulometrie#3', 'card:08-voltammetrie-coulometrie:0b5zlpr'),
    ('analytical-chemistry-1', '08-voltammetrie-coulometrie#4', 'card:08-voltammetrie-coulometrie:1f5wafc'),
    ('analytical-chemistry-1', '08-voltammetrie-coulometrie#5', 'card:08-voltammetrie-coulometrie:1jt9ck3'),
    ('analytical-chemistry-1', '09-chemosensoren#0', 'card:09-chemosensoren:05mwoai'),
    ('analytical-chemistry-1', '09-chemosensoren#1', 'card:09-chemosensoren:1a1gdq6'),
    ('analytical-chemistry-1', '09-chemosensoren#2', 'card:09-chemosensoren:06cm2gs'),
    ('analytical-chemistry-1', '09-chemosensoren#3', 'card:09-chemosensoren:1bmz0cm'),
    ('analytical-chemistry-1', '09-chemosensoren#4', 'card:09-chemosensoren:1y79ufz'),
    ('analytical-chemistry-1', '09-chemosensoren#5', 'card:09-chemosensoren:07zvkds'),
    ('analytical-chemistry-1', '10-statistik-qualitaet#0', 'card:10-statistik-qualitaet:10cf2d6'),
    ('analytical-chemistry-1', '10-statistik-qualitaet#1', 'card:10-statistik-qualitaet:1bv0eb7'),
    ('analytical-chemistry-1', '10-statistik-qualitaet#2', 'card:10-statistik-qualitaet:01mo26p'),
    ('analytical-chemistry-1', '10-statistik-qualitaet#3', 'card:10-statistik-qualitaet:10ms8qx'),
    ('analytical-chemistry-1', '10-statistik-qualitaet#4', 'card:10-statistik-qualitaet:1d7zg4o'),
    ('analytical-chemistry-1', '10-statistik-qualitaet#5', 'card:10-statistik-qualitaet:0jzrm0y'),
    ('analytical-chemistry-1', '11-saeurebase-ph#0', 'card:11-saeurebase-ph:1btyvq4'),
    ('analytical-chemistry-1', '11-saeurebase-ph#1', 'card:11-saeurebase-ph:0hppdmo'),
    ('analytical-chemistry-1', '11-saeurebase-ph#2', 'card:11-saeurebase-ph:0bbhvc0'),
    ('analytical-chemistry-1', '11-saeurebase-ph#3', 'card:11-saeurebase-ph:0nf98ws'),
    ('analytical-chemistry-1', '11-saeurebase-ph#4', 'card:11-saeurebase-ph:18f31up'),
    ('analytical-chemistry-1', '11-saeurebase-ph#5', 'card:11-saeurebase-ph:11eel07'),
    ('analytical-chemistry-1', '12-faellungsreaktionen#0', 'card:12-faellungsreaktionen:0jwdyrb'),
    ('analytical-chemistry-1', '12-faellungsreaktionen#1', 'card:12-faellungsreaktionen:1mrtmjs'),
    ('analytical-chemistry-1', '12-faellungsreaktionen#2', 'card:12-faellungsreaktionen:1jp4bgx'),
    ('analytical-chemistry-1', '12-faellungsreaktionen#3', 'card:12-faellungsreaktionen:0fcqxnk'),
    ('analytical-chemistry-1', '12-faellungsreaktionen#4', 'card:12-faellungsreaktionen:1akzsky'),
    ('analytical-chemistry-1', '13-chromatographie-grundlagen#0', 'card:13-chromatographie-grundlagen:0klzclp'),
    ('analytical-chemistry-1', '13-chromatographie-grundlagen#1', 'card:13-chromatographie-grundlagen:0a4h4go'),
    ('analytical-chemistry-1', '13-chromatographie-grundlagen#2', 'card:13-chromatographie-grundlagen:0yst425'),
    ('analytical-chemistry-1', '13-chromatographie-grundlagen#3', 'card:13-chromatographie-grundlagen:0d7xu3n'),
    ('analytical-chemistry-1', '13-chromatographie-grundlagen#4', 'card:13-chromatographie-grundlagen:0xtqwn2'),
    ('analytical-chemistry-1', '13-chromatographie-grundlagen#5', 'card:13-chromatographie-grundlagen:0j0ttvc'),
    ('analytical-chemistry-1', '14-trennverfahren-gc-hplc#0', 'card:14-trennverfahren-gc-hplc:1b898cz'),
    ('analytical-chemistry-1', '14-trennverfahren-gc-hplc#1', 'card:14-trennverfahren-gc-hplc:18866hb'),
    ('analytical-chemistry-1', '14-trennverfahren-gc-hplc#2', 'card:14-trennverfahren-gc-hplc:1ssrw4o'),
    ('analytical-chemistry-1', '14-trennverfahren-gc-hplc#3', 'card:14-trennverfahren-gc-hplc:00tlng0'),
    ('analytical-chemistry-1', '14-trennverfahren-gc-hplc#4', 'card:14-trennverfahren-gc-hplc:02ulbga'),
    ('analytical-chemistry-1', '14-trennverfahren-gc-hplc#5', 'card:14-trennverfahren-gc-hplc:0jo5u38'),
    ('analytical-chemistry-1', '15-kalibrierung-standardaddition#0', 'card:15-kalibrierung-standardaddition:1budcvm'),
    ('analytical-chemistry-1', '15-kalibrierung-standardaddition#1', 'card:15-kalibrierung-standardaddition:1pmoffs'),
    ('analytical-chemistry-1', '15-kalibrierung-standardaddition#2', 'card:15-kalibrierung-standardaddition:1m72vlf'),
    ('analytical-chemistry-1', '15-kalibrierung-standardaddition#3', 'card:15-kalibrierung-standardaddition:18pr0xq'),
    ('analytical-chemistry-1', '16-atomspektrometrie#0', 'card:16-atomspektrometrie:0mvkilc'),
    ('analytical-chemistry-1', '16-atomspektrometrie#1', 'card:16-atomspektrometrie:02leb1m'),
    ('analytical-chemistry-1', '16-atomspektrometrie#2', 'card:16-atomspektrometrie:1gthgj4'),
    ('analytical-chemistry-1', '16-atomspektrometrie#3', 'card:16-atomspektrometrie:1940k5g'),
    ('analytical-chemistry-1', '17-elektroden-faellungstitration#0', 'card:17-elektroden-faellungstitration:0uzyeji'),
    ('analytical-chemistry-1', '17-elektroden-faellungstitration#1', 'card:17-elektroden-faellungstitration:0r86tgg'),
    ('analytical-chemistry-1', '17-elektroden-faellungstitration#2', 'card:17-elektroden-faellungstitration:0a1s9cy'),
    ('analytical-chemistry-1', '17-elektroden-faellungstitration#3', 'card:17-elektroden-faellungstitration:1cbvcf0'),
    ('analytical-chemistry-1', '18-fehlerrechnung#0', 'card:18-fehlerrechnung:19fahm6'),
    ('analytical-chemistry-1', '18-fehlerrechnung#1', 'card:18-fehlerrechnung:0de3zex'),
    ('analytical-chemistry-1', '18-fehlerrechnung#2', 'card:18-fehlerrechnung:16rrnhr'),
    ('analytical-chemistry-1', '18-fehlerrechnung#3', 'card:18-fehlerrechnung:0rn311e'),
    ('organic-chemistry', '01-introduction#0', 'card:01-introduction:10z74oc'),
    ('organic-chemistry', '01-introduction#1', 'card:01-introduction:13x0m4z'),
    ('organic-chemistry', '01-introduction#2', 'card:01-introduction:15q9i2y'),
    ('organic-chemistry', '01-introduction#3', 'card:01-introduction:07bbr3p'),
    ('organic-chemistry', '01-introduction#4', 'card:01-introduction:0xgsj8o'),
    ('organic-chemistry', '01-introduction#5', 'card:01-introduction:1k2wdlg'),
    ('organic-chemistry', '01-introduction#6', 'card:01-introduction:1sndyzy'),
    ('organic-chemistry', '01-introduction#7', 'card:01-introduction:1mrboe9'),
    ('organic-chemistry', '02-pyridines#0', 'card:02-pyridines:02lwqyt'),
    ('organic-chemistry', '02-pyridines#1', 'card:02-pyridines:1cv4imb'),
    ('organic-chemistry', '02-pyridines#2', 'card:02-pyridines:1uvjmpz'),
    ('organic-chemistry', '02-pyridines#3', 'card:02-pyridines:1yj82fg'),
    ('organic-chemistry', '02-pyridines#4', 'card:02-pyridines:08mcu70'),
    ('organic-chemistry', '02-pyridines#5', 'card:02-pyridines:1k1pd51'),
    ('organic-chemistry', '02-pyridines#6', 'card:02-pyridines:1nr4uj3'),
    ('organic-chemistry', '02-pyridines#7', 'card:02-pyridines:0ab3tka'),
    ('organic-chemistry', '03-five-ring-one-heteroatom#0', 'card:03-five-ring-one-heteroatom:057rsia'),
    ('organic-chemistry', '03-five-ring-one-heteroatom#1', 'card:03-five-ring-one-heteroatom:03q12nj'),
    ('organic-chemistry', '03-five-ring-one-heteroatom#2', 'card:03-five-ring-one-heteroatom:0y0jy5n'),
    ('organic-chemistry', '03-five-ring-one-heteroatom#3', 'card:03-five-ring-one-heteroatom:0raujxk'),
    ('organic-chemistry', '03-five-ring-one-heteroatom#4', 'card:03-five-ring-one-heteroatom:0w17y2c'),
    ('organic-chemistry', '03-five-ring-one-heteroatom#5', 'card:03-five-ring-one-heteroatom:1o6094w'),
    ('organic-chemistry', '04-five-ring-two-heteroatoms#0', 'card:04-five-ring-two-heteroatoms:0lzzg26'),
    ('organic-chemistry', '04-five-ring-two-heteroatoms#1', 'card:04-five-ring-two-heteroatoms:1lxpmi3'),
    ('organic-chemistry', '04-five-ring-two-heteroatoms#2', 'card:04-five-ring-two-heteroatoms:0sijthb'),
    ('organic-chemistry', '04-five-ring-two-heteroatoms#3', 'card:04-five-ring-two-heteroatoms:1mvgf0v'),
    ('organic-chemistry', '04-five-ring-two-heteroatoms#4', 'card:04-five-ring-two-heteroatoms:08d9i0z'),
    ('organic-chemistry', '04-five-ring-two-heteroatoms#5', 'card:04-five-ring-two-heteroatoms:0qh8cjr'),
    ('organic-chemistry', '05-cycloadditions#0', 'card:05-cycloadditions:1icba6a'),
    ('organic-chemistry', '05-cycloadditions#1', 'card:05-cycloadditions:11ru87j'),
    ('organic-chemistry', '05-cycloadditions#2', 'card:05-cycloadditions:1cv4imb'),
    ('organic-chemistry', '05-cycloadditions#3', 'card:05-cycloadditions:0adoh5e'),
    ('organic-chemistry', '05-cycloadditions#4', 'card:05-cycloadditions:0i3pq53'),
    ('organic-chemistry', '05-cycloadditions#5', 'card:05-cycloadditions:1xgxlfr'),
    ('organic-chemistry', '06-cyclocondensations#0', 'card:06-cyclocondensations:1bqsez5'),
    ('organic-chemistry', '06-cyclocondensations#1', 'card:06-cyclocondensations:0k94jy7'),
    ('organic-chemistry', '06-cyclocondensations#2', 'card:06-cyclocondensations:1uvjmpz'),
    ('organic-chemistry', '06-cyclocondensations#3', 'card:06-cyclocondensations:07k6u7x'),
    ('organic-chemistry', '06-cyclocondensations#4', 'card:06-cyclocondensations:08fisvj'),
    ('organic-chemistry', '06-cyclocondensations#5', 'card:06-cyclocondensations:1vwbl7q'),
    ('organic-chemistry', '07-sear-regioselectivity#0', 'card:07-sear-regioselectivity:17pa0nq'),
    ('organic-chemistry', '07-sear-regioselectivity#1', 'card:07-sear-regioselectivity:03v55f7'),
    ('organic-chemistry', '07-sear-regioselectivity#2', 'card:07-sear-regioselectivity:0r3shel'),
    ('organic-chemistry', '07-sear-regioselectivity#3', 'card:07-sear-regioselectivity:18mbgop'),
    ('organic-chemistry', '07-sear-regioselectivity#4', 'card:07-sear-regioselectivity:08p5w0q'),
    ('organic-chemistry', '08-mechanisms#0', 'card:08-mechanisms:1cr1y11'),
    ('organic-chemistry', '08-mechanisms#1', 'card:08-mechanisms:161hm3o'),
    ('organic-chemistry', '08-mechanisms#2', 'card:08-mechanisms:0q1ls99'),
    ('organic-chemistry', '08-mechanisms#3', 'card:08-mechanisms:103q59m'),
    ('organic-chemistry', '08-mechanisms#4', 'card:08-mechanisms:1mh0qak'),
    ('organic-chemistry', '09-bioisosteres-skeletal-editing#0', 'card:09-bioisosteres-skeletal-editing:04ux8hd'),
    ('organic-chemistry', '09-bioisosteres-skeletal-editing#1', 'card:09-bioisosteres-skeletal-editing:1214770'),
    ('organic-chemistry', '09-bioisosteres-skeletal-editing#2', 'card:09-bioisosteres-skeletal-editing:02q2ia4'),
    ('organic-chemistry', '09-bioisosteres-skeletal-editing#3', 'card:09-bioisosteres-skeletal-editing:1plx016'),
    ('organic-chemistry', '09-bioisosteres-skeletal-editing#4', 'card:09-bioisosteres-skeletal-editing:0834fjd'),
    ('organic-chemistry', '09-bioisosteres-skeletal-editing#5', 'card:09-bioisosteres-skeletal-editing:0b8rkzl')
  ) as u(course_id, alt, neu)
 where r.item_type = 'card'
   and r.course_id = u.course_id
   and r.item_id   = u.alt;

-- 2. Fragen mit Präfix versehen. Wiederholbar.
update reviews
   set item_id = 'q:' || item_id
 where item_type = 'question'
   and item_id not like 'q:%';

-- 3. Karten, die sich nicht zuordnen lassen, wegräumen statt falsch stehen zu
--    lassen: ein Plan, der auf die falsche Karte zeigt, ist schlechter als keiner.
delete from reviews
 where item_type = 'card'
   and item_id not like 'card:%';
